#!/usr/bin/env bash

set -euo pipefail

command -v git-lfs >/dev/null 2>&1 || {
  printf >&2 "\nGit LFS is required by this repository but was not found on PATH.\n\n"
  exit 2
}

git lfs post-commit "$@"
